name: Build & Test

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Ensures everything is formatted properly.
      run: cargo fmt --all -- --check
  clippy:
    runs-on: ubuntu-latest
    needs: fmt
    steps:
    - uses: actions/checkout@v2
    - name: Sets of lints used by default to make code cleaner.
      run: cargo clippy --all -- -A clippy::all
  build:
    runs-on: ubuntu-latest
    needs: clippy
    steps:
    - uses: actions/checkout@v2
    - name: Ensures the code builds.
      run: cargo build --verbose
  test:
    runs-on: ubuntu-latest
    needs: clippy
    steps:
    - uses: actions/checkout@v2
    - name: Ensures tests are all passing.
      run: cargo test --all --verbose