name: Build & Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master


env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Ensures everything is formatted properly.
      run: cargo fmt --all -- --check
  clippy:
    runs-on: ubuntu-latest
    needs: fmt
    steps:
    - uses: actions/checkout@v2
    - name: Sets of lints used by default to make code cleaner.
      run: cargo clippy --all-targets --all-features -- -D clippy::pedantic
  build:
    runs-on: ubuntu-latest
    needs: clippy
    steps:
    - uses: actions/checkout@v2
    - name: Ensures the code builds.
      run: cargo build
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: install ripgrep
      run: cargo install ripgrep
    - name: Ensures tests are all passing.
      run: cargo test --all